# Autogenerated wrapper script for cryptopp_jll for x86_64-apple-darwin
export libcryptopp

JLLWrappers.@generate_wrapper_header("cryptopp")
JLLWrappers.@declare_library_product(libcryptopp, "@rpath/libcryptopp.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcryptopp,
        "lib/libcryptopp.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
